### ISSUE TITLE
Pip install fails on linux virtual environment

### ISSUE THREAD

**Issue by EdwinRor** [sirfz/tesserocr#14]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lqe1qy/tesserocr/
###################################
Collecting tesserocr
  Downloading tesserocr-2.1.1.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 3.1MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/tesserocr.egg-info
    writing pip-egg-info/tesserocr.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/tesserocr.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/tesserocr.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/tesserocr.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Package lept was not found in the pkg-config search path.
    Perhaps you should add the directory containing `lept.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'lept' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lqe1qy/tesserocr/setup.py", line 163, in <module>
        test_suite='tests'
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/dist.py", line 929, in run_commands
        self.run_command(cmd)
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/dist.py", line 948, in run_command
        cmd_obj.run()
      File "/var/lib/openshift/573147277628e1669600012d/python/virtenv/venv/lib/python3.3/site-packages/setuptools-22.0.5-py3.3.egg/setuptools/command/egg_info.py", line 193, in run
      File "/var/lib/openshift/573147277628e1669600012d/python/virtenv/venv/lib/python3.3/site-packages/setuptools-22.0.5-py3.3.egg/setuptools/command/egg_info.py", line 216, in find_sources
      File "/var/lib/openshift/573147277628e1669600012d/python/virtenv/venv/lib/python3.3/site-packages/setuptools-22.0.5-py3.3.egg/setuptools/command/egg_info.py", line 300, in run
      File "/var/lib/openshift/573147277628e1669600012d/python/virtenv/venv/lib/python3.3/site-packages/setuptools-22.0.5-py3.3.egg/setuptools/command/egg_info.py", line 329, in add_defaults
      File "/var/lib/openshift/573147277628e1669600012d/python/virtenv/venv/lib/python3.3/site-packages/setuptools-22.0.5-py3.3.egg/setuptools/command/sdist.py", line 132, in add_defaults
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/dist.py", line 821, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "/var/lib/openshift/573147277628e1669600012d/python/virtenv/venv/lib/python3.3/site-packages/setuptools-22.0.5-py3.3.egg/setuptools/__init__.py", line 132, in __init__
      File "/opt/rh/python33/root/usr/lib64/python3.3/distutils/cmd.py", line 62, in __init__
        self.initialize_options()
      File "/tmp/pip-build-lqe1qy/tesserocr/setup.py", line 117, in initialize_options
        build_args = package_config()
      File "/tmp/pip-build-lqe1qy/tesserocr/setup.py", line 72, in package_config
        opt = options[f[:2]]
    KeyError: '-g'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lqe1qy/tesserocr/

**Comment by sirfz** [comment]
I see two issues in the output. First, you seem to not have leptonica installed or it was not detected by pkg-config for some reason.

Second issue is with the setup script crashing with KeyError when an unexpected option is output by pkg-config. I just pushed a fix for this one, please try the installation from the Github repo (but make sure you have tesseract and leptonica installed as per the README).

**Comment by EdwinRor** [comment]
I still can't get it to install.
#####################
tesseract -v
tesseract 3.02.02
 leptonica-1.73
  libgif 4.1.6(?) : libjpeg 6b (libjpeg-turbo 1.2.1) : libpng 1.2.49 : libtiff 3.9.4 : zlib 1.2.3
#### Looks like tesseract and leptonica are there but i get this
Command "/var/lib/openshift/573147277628e1669600012d/python/virtenv/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-fb5fa_-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-q_2jsg-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/lib/openshift/573147277628e1669600012d/python/virtenv/venv/include/site/python3.3/tesserocr" failed with error code 1 in /tmp/pip-fb5fa_-build/

**Comment by sirfz** [comment]
The error doesn't say much (perhaps we'll get more info if you try `python setup.py build_ext`). However, tesserocr requires [tesseract v3.04.00](https://github.com/tesseract-ocr/tesseract/releases) or greater to successfully compile.

**Comment by EdwinRor** [comment]
Thank you. Fixed.

tesseract 3.04.01
 leptonica-1.73
  libgif 4.1.6(?) : libjpeg 6b (libjpeg-turbo 1.2.1) : libpng 1.2.49 : libtiff 3.9.4 : zlib 1.2.3
